RESULTS_PATH = "../results/"
PRETRAINED_MODEL_PATH = "../results/pretrained_model/"
MODELS_PATH = "../models/"
CORD_FINETUNING_EPOCH = 5
CORD_FINETUNING_BATCH_SIZE = 16
CORD_SCIBERT_MODEL_NAME = "COVID-scibert-latest"
CORD_19_BLOCK_SIZE = 256
NER_MAX_LENGTH = 256
